//======---------------------------------------------------------------======//
//                                                                           //
// Copyright 2021 Evan Cox <evanacox00@gmail.com>. All rights reserved.      //
//                                                                           //
// Use of this source code is governed by a BSD-style license that can be    //
// found in the LICENSE.txt file at the root of this project, or at the      //
// following link: https://opensource.org/licenses/BSD-3-Clause              //
//                                                                           //
//======---------------------------------------------------------------======//
#pragma once

#include "../core/error_reporting.h"
#include <antlr4-runtime.h>
#include <filesystem>
#include <optional>

namespace gal {
  /// Helps to improve general ANTLR parse errors from the terrible default
  /// that they produce
  class ParserErrorListener final : public antlr4::BaseErrorListener {
  public:
    /// Creates a ParserErrorListener.
    ///
    /// \param file The file being parsed
    explicit ParserErrorListener(std::filesystem::path file) noexcept;

    void syntaxError(antlr4::Recognizer* recognizer,
        antlr4::Token* token,
        size_t line,
        size_t col,
        const std::string&,
        std::exception_ptr) final;

    /// Gets the errors generated by parsing
    ///
    /// \return The errors generated by parsing
    std::optional<std::vector<gal::Diagnostic>> errors() noexcept;

  private:
    /// Pushes an error into the internal error list
    ///
    /// \param diagnostics The parts of the diagnostic message
    void push_error(std::vector<std::unique_ptr<gal::DiagnosticPart>> diagnostics) noexcept;

    std::vector<gal::Diagnostic> diagnostics_;
    std::filesystem::path file_;
  };
} // namespace gal
