# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Compilers 101
email: evanacox00@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A website for my high school senior project, containing journal entries,
  explanations and writing, and technical documentation. 
baseurl: "/honors-forum-project" # the subpath of your site, e.g. /blog
url: "https://pages.evanacox.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  evanacox
remote_theme: pmarsceill/just-the-docs

color_scheme: blue

# Build settings
plugins: []

heading_anchors: true
back_to_top: true
back_to_top_text: "Back to Top"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

footer_content: "Copyright &copy; 2021, Evan Cox. All rights reserved. Distributed under the <a href=\"https://github.com/evanacox/honors-forum-project/tree/master/LICENSE.txt\">BSD 3-clause license.</a>"

search_enabled: true
search:
  button: true

aux_links:
  "Source Code on GitHub":
    - "https://github.com/evanacox/honors-forum-project"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
